image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  HEROKU_APP_NAME: lit-springs-09878
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web

stages:
  - build

docker-build:
  stage: build
  script:
    - apk add --no-cache curl
    - sudo docker build
        --tag $HEROKU_REGISTRY_IMAGE
        --file ./Dockerfile
        "."
    - sudo docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - sudo docker push $HEROKU_REGISTRY_IMAGE
    - ./release.sh
